#!/bin/bash
set -ex

pip install matplotlib==3.5.1
cd /home/jovyan
mkdir tutorial
mv src tutorial
mv *.toml tutorial
git clone https://github.com/dmalyuta/SCPToolbox.jl.git
cd SCPToolbox.jl
git checkout dev/binder
cd ../tutorial/src
julia -e 'using Pkg; Pkg.activate(".."); Pkg.develop(path="../../SCPToolbox.jl/"); Pkg.precompile()'
